document.addEventListener('DOMContentLoaded', function() {
    const inputLine = document.getElementById('input-line');
    const terminalOutput = document.getElementById('terminal-output');
    const promptElement = document.querySelector('.prompt'); 
    let currentDirectory = '~'; 

    inputLine.addEventListener('keydown', function(event) {
        if (event.key === 'Enter') {
            let inputValue = inputLine.value.trim();
            terminalOutput.innerHTML += `<div><span class="username">matthew@kali</span>:${currentDirectory}$ ${inputValue}</div>`;
            processCommand(inputValue);
            inputLine.value = '';
            setTimeout(scrollToBottom, 0);  // Ensure scroll happens after rendering
        }
    });

    function processCommand(command) {
        let output = '';

        switch (command.toLowerCase()) {
            case 'help':
                output = 'Available commands: ls, cd, cat, clear, help, whoami';
                break;
            case 'whoami':
                output = 'I’m Matthew Hjørnevik-Saunders, a 25-year-old with a background in cybersecurity. I studied at Universitetet i Bergen and Zhejiang University, where I gained practical experience in areas like secure coding and vulnerability analysis. I’m passionate about understanding how technology works and how to make it safer for everyone.';
                break;
            case 'ls':
                if (currentDirectory === '~') {
                    output = 'projects  README.md';
                } else if (currentDirectory === '~/projects') {
                    output = 'VulnHunter.txt    LLM-Security.txt    iOS-app-scraping.txt';
                } else {
                    output = '';
                }
                break;
            case 'cd projects':
                if (currentDirectory === '~') {
                    currentDirectory = '~/projects';
                    updatePrompt();
                    output = ''; 
                } else {
                    output = 'cd: no such file or directory: projects';
                }
                break;
            case 'cd ..':
                if (currentDirectory === '~/projects') {
                    currentDirectory = '~';
                    updatePrompt();
                }
                output = ''; 
                break;
            case 'cat readme.md':
                if (currentDirectory === '~') {
                    output = 'Welcome to my cybersecurity portfolio!';
                } else {
                    output = 'cat: README.md: No such file or directory';
                }
                break;
            case 'cat vulnhunter.txt':
                if (currentDirectory === '~/projects') {
                    output = 'WORK IN PROGRESS!<br>A tool for automatically detecting common web application vulnerabilities such as SQL injection (SQLi), Cross-Site Scripting (XSS), and Cross-Site Request Forgery (CSRF).<br><a href="https://github.com/MatthewHJS/VulnHunter" target="_blank">https://github.com/MatthewHJS/VulnHunter</a>';
                } else {
                    output = 'cat: vulnhunter.txt: No such file or directory';
                }
                break;
            case 'cat llm-security.txt':
                if (currentDirectory === '~/projects') {
                    output = 'A project conducted at Zhejiang University, focusing on the security assessment of code generated by various Large Language Models (LLMs).<br><a href="https://github.com/MatthewHJS/LLM-Code-Security-Analysis" target="_blank">https://github.com/MatthewHJS/LLM-Code-Security-Analysis</a>';
                } else {
                    output = 'cat: llm-security.txt: No such file or directory';
                }
                break;
            case 'cat ios-app-scraping.txt':
                if (currentDirectory === '~/projects') {
                    output = 'Research project conducted at Zhejiang University, focusing on collecting and analyzing data on iOS apps, with a specific focus on the mechanisms of the You Might Also Like feature in the App Store.<br><a href="https://github.com/MatthewHJS/iOS-app-data-collection-analysis" target="_blank">https://github.com/MatthewHJS/iOS-app-data-collection-analysis</a>';
                } else {
                    output = 'cat: ios-app-scraping.txt: No such file or directory';
                }
                break;
            case 'clear':
                terminalOutput.innerHTML = '';
                break;
            default:
                output = `${command}: command not found`;
                break;
        }

        if (command.toLowerCase() !== 'clear') {
            terminalOutput.innerHTML += `<div>${output}</div>`;
        }

        setTimeout(scrollToBottom, 0);  // Ensure scroll happens after rendering
    }

    function updatePrompt() {
        promptElement.innerHTML = `(matthew@kali:${currentDirectory}$)`;
    }

    function scrollToBottom() {
        terminalOutput.scrollTop = terminalOutput.scrollHeight;
    }

    updatePrompt();
});
